// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: root_manager.proto

package com.defyun.pb;

public final class RootManagerProtocol {
  private RootManagerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RunRootCmdReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:root_manager.RunRootCmdReq)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();
  }
  /**
   * Protobuf type {@code root_manager.RunRootCmdReq}
   */
  public  static final class RunRootCmdReq extends
      com.google.protobuf.GeneratedMessageLite<
          RunRootCmdReq, RunRootCmdReq.Builder> implements
      // @@protoc_insertion_point(message_implements:root_manager.RunRootCmdReq)
      RunRootCmdReqOrBuilder {
    private RunRootCmdReq() {
      cmd_ = "";
    }
    public static final int CMD_FIELD_NUMBER = 1;
    private java.lang.String cmd_;
    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      return cmd_;
    }
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(cmd_);
    }
    /**
     * <code>string cmd = 1;</code>
     * @param value The cmd to set.
     */
    private void setCmd(
        java.lang.String value) {
      value.getClass();
  
      cmd_ = value;
    }
    /**
     * <code>string cmd = 1;</code>
     */
    private void clearCmd() {
      
      cmd_ = getDefaultInstance().getCmd();
    }
    /**
     * <code>string cmd = 1;</code>
     * @param value The bytes for cmd to set.
     */
    private void setCmdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      cmd_ = value.toStringUtf8();
      
    }

    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.defyun.pb.RootManagerProtocol.RunRootCmdReq prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code root_manager.RunRootCmdReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.defyun.pb.RootManagerProtocol.RunRootCmdReq, Builder> implements
        // @@protoc_insertion_point(builder_implements:root_manager.RunRootCmdReq)
        com.defyun.pb.RootManagerProtocol.RunRootCmdReqOrBuilder {
      // Construct using com.defyun.pb.RootManagerProtocol.RunRootCmdReq.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string cmd = 1;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public java.lang.String getCmd() {
        return instance.getCmd();
      }
      /**
       * <code>string cmd = 1;</code>
       * @return The bytes for cmd.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getCmdBytes() {
        return instance.getCmdBytes();
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        copyOnWrite();
        instance.setCmd(value);
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        copyOnWrite();
        instance.clearCmd();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCmdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:root_manager.RunRootCmdReq)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.defyun.pb.RootManagerProtocol.RunRootCmdReq();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "cmd_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.defyun.pb.RootManagerProtocol.RunRootCmdReq> parser = PARSER;
          if (parser == null) {
            synchronized (com.defyun.pb.RootManagerProtocol.RunRootCmdReq.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.defyun.pb.RootManagerProtocol.RunRootCmdReq>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:root_manager.RunRootCmdReq)
    private static final com.defyun.pb.RootManagerProtocol.RunRootCmdReq DEFAULT_INSTANCE;
    static {
      RunRootCmdReq defaultInstance = new RunRootCmdReq();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RunRootCmdReq.class, defaultInstance);
    }

    public static com.defyun.pb.RootManagerProtocol.RunRootCmdReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RunRootCmdReq> PARSER;

    public static com.google.protobuf.Parser<RunRootCmdReq> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RunRootCmdRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:root_manager.RunRootCmdResp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code root_manager.RunRootCmdResp}
   */
  public  static final class RunRootCmdResp extends
      com.google.protobuf.GeneratedMessageLite<
          RunRootCmdResp, RunRootCmdResp.Builder> implements
      // @@protoc_insertion_point(message_implements:root_manager.RunRootCmdResp)
      RunRootCmdRespOrBuilder {
    private RunRootCmdResp() {
      result_ = "";
    }
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.lang.String result_;
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      return result_;
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(result_);
    }
    /**
     * <code>string result = 1;</code>
     * @param value The result to set.
     */
    private void setResult(
        java.lang.String value) {
      value.getClass();
  
      result_ = value;
    }
    /**
     * <code>string result = 1;</code>
     */
    private void clearResult() {
      
      result_ = getDefaultInstance().getResult();
    }
    /**
     * <code>string result = 1;</code>
     * @param value The bytes for result to set.
     */
    private void setResultBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      result_ = value.toStringUtf8();
      
    }

    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.defyun.pb.RootManagerProtocol.RunRootCmdResp prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code root_manager.RunRootCmdResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.defyun.pb.RootManagerProtocol.RunRootCmdResp, Builder> implements
        // @@protoc_insertion_point(builder_implements:root_manager.RunRootCmdResp)
        com.defyun.pb.RootManagerProtocol.RunRootCmdRespOrBuilder {
      // Construct using com.defyun.pb.RootManagerProtocol.RunRootCmdResp.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public java.lang.String getResult() {
        return instance.getResult();
      }
      /**
       * <code>string result = 1;</code>
       * @return The bytes for result.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getResultBytes() {
        return instance.getResultBytes();
      }
      /**
       * <code>string result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        copyOnWrite();
        instance.setResult(value);
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        copyOnWrite();
        instance.clearResult();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResultBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:root_manager.RunRootCmdResp)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.defyun.pb.RootManagerProtocol.RunRootCmdResp();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "result_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.defyun.pb.RootManagerProtocol.RunRootCmdResp> parser = PARSER;
          if (parser == null) {
            synchronized (com.defyun.pb.RootManagerProtocol.RunRootCmdResp.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.defyun.pb.RootManagerProtocol.RunRootCmdResp>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:root_manager.RunRootCmdResp)
    private static final com.defyun.pb.RootManagerProtocol.RunRootCmdResp DEFAULT_INSTANCE;
    static {
      RunRootCmdResp defaultInstance = new RunRootCmdResp();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RunRootCmdResp.class, defaultInstance);
    }

    public static com.defyun.pb.RootManagerProtocol.RunRootCmdResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RunRootCmdResp> PARSER;

    public static com.google.protobuf.Parser<RunRootCmdResp> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
